# https://github.com/peaceiris/actions-hugo
# https://github.com/peaceiris/actions-gh-pages
# https://github.com/peaceiris/hugo-extended-docker

name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-schedule-and-manual-deployment
  # for deploying on a cron schedule
  schedule:
    - cron: "22 22 * * *"
  # for deploying manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
